project:
  type: website

website:
  title: "Your Name"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "Blog"
        href: blog.qmd

format:
  html:
    theme: default
    css: styles.css